In [ ]:
import numpy as np
import pandas as pd

In [ ]:
assessements=pd.read_csv('assessements_cleaned.csv')
cp_scores=pd.read_csv('checkpoint_scores_durations_cleaned.csv')
oto=pd.read_csv('one_to_one_cleaned.csv')

In [ ]:
occ_cp=cp_scores['student id'].value_counts(sort=False).to_dict()

In [ ]:
cp_scores['checkpoints mean']=cp_scores['student id']
cp_scores['checkpoints mean']=cp_scores.drop(columns='student id').replace(occ_cp)['checkpoints mean']
cp_scores_grouped=cp_scores.groupby(['student id']).mean()

In [ ]:
occ=assessements['student id'].value_counts(sort=False).to_dict()

In [ ]:
assessements['assessements mean']=assessements['student id']
assessements['assessements mean']=assessements.drop(columns='student id').replace(occ)['assessements mean']

In [ ]:
assessements_grouped=assessements.groupby(['student id']).mean()

In [ ]:
dataset = pd.merge(assessements_grouped, cp_scores_grouped,right_index=True, left_index=True)

In [ ]:
dataset

                                      isRetaken  ...  checkpoints mean
student id                                       ...
01fb9b25-affe-4469-8060-534c198e769b   0.482759  ...                 6
0726b6b8-fcd2-4abf-ac28-30972c936531   0.909091  ...                 8
0989df56-ae4c-49d8-90da-484aad6b9a4b   0.954545  ...                 8
0bb9a9a3-323f-4d76-821c-3307a9b321f8   0.592593  ...                 2
0cebb3ce-aabe-423e-af68-81ac8ced5da6   0.765957  ...                 1
...                                         ...  ...               ...
f56f7e09-d217-4055-ae95-404fdfe21a00   0.772727  ...                 8
f5f3eb80-f612-46a7-9a47-b732c6f86a9c   0.925926  ...                 1
f86b230c-75b1-4942-b7f9-c04bc67e13a2   0.914894  ...                 1
fefaaea9-c6a9-4e55-bf46-86f86964d725   0.863636  ...                 3
ff27a272-d123-4b8a-b681-f17fce758a74   0.800000  ...                 3

[114 rows x 13 columns]

In [ ]:
dataset.corr()

                              isRetaken  ...  checkpoints mean
isRetaken                      1.000000  ...          0.060114
c.averageScore                -0.252686  ...         -0.112456
first score                   -0.151538  ...          0.043054
skill understanding duration   0.167873  ...          0.067644
duration of assessement        0.073941  ...          0.126218
number of switches            -0.136849  ...         -0.171056
assessements mean              0.042781  ...          0.704532
score                         -0.111100  ...          0.036200
quality score                 -0.112782  ...          0.018332
problem solving score         -0.113565  ...          0.039693
technical score               -0.101000  ...          0.048443
checkpoint_duration            0.198184  ...         -0.209495
checkpoints mean               0.060114  ...          1.000000

[13 rows x 13 columns]

In [ ]:
import numpy as np
np.trunc(np.random.normal(0,3,100))

array([-0.,  2.,  1.,  2., -4.,  2.,  2.,  0.,  1.,  0., -1.,  0.,  5.,
       -2., -1., -2.,  2., -3., -1., -0.,  2., -1.,  1., -2.,  0., -1.,
        0., -0., -3.,  2., -0.,  0., -1., -1.,  4.,  1.,  0., -2.,  6.,
        2.,  2., -2., -1.,  2.,  2.,  2., -0.,  3., -1.,  2.,  6.,  3.,
       -0., -2., -3.,  1.,  1., -4.,  1.,  1.,  4.,  2.,  1.,  1.,  4.,
        4., -0.,  0., -0.,  4.,  3.,  0.,  0.,  1.,  0.,  0., -4., -0.,
        5.,  0., -0.,  1., -2., -6., -2., -0.,  2.,  4., -7., -1., -2.,
       -1.,  3.,  2.,  1.,  0., -3., -1.,  1., -2.])

In [ ]:
ch='acwxc'
ch.

TypeError: ignored